### ISSUE TITLE
Character File Format

### ISSUE THREAD

**Issue by jjpearson8611** [brndmfrd/PFCharacterSheet#2]
The format of character sheet files (.pf) needs to be defined.
I was thinking .json for obvious reasons.
This being said should we divide up the .json based on the tabs of the program?

**Comment by brndmfrd** [comment]
Models and Modules --
Regarding your text:

File management (reading, writing, loading character ui, and creating
character ui) is all offloaded into one module, the StartupScreen Module.

The ActiveCharacter class is reserved as a central static model to be used
by the business layers (models) of each individual module.

---

Regarding file format:
I agree with json format.  I don't think the file will ever be of any
significant size, so compression will likely not be necessary.

When the saved character file is read into the application, all of the
values should go directly to the Active Character model that acts as a
container for all the values to be used by each individual module. Since we
have all values going to one file, it would follow that the data be
structured relative to how the container is structured.

**Comment by jjpearson8611** [comment]
I'm confused why the active character class is static.
Is it just because we don't wanna pass around the object?

**Comment by brndmfrd** [comment]
The idea is to have one static class that holds all the primitive data (ST, DEX, HP, Skill ranks, etc) to be referenced by the modules. 
Since only one character sheet is to be active at one time, there is only one active character class. 

If we had more data to hold, we might have a database.  The models of the individual modules would interact with the db layer to abstract the
business logic from what is contained in a view.  Instead of a database to share, we have this static class.
